In [1]:
import pandas as pd

In [5]:
from os import listdir
from os.path import isfile, join
onlyfiles = [f for f in listdir('archive') if isfile(join('archive', f))] # поиск всех файлов с данными

In [6]:
book = pd.DataFrame(columns=['Id', 'Name', 'Authors', 'ISBN', 'Rating', 'PublishYear',
       'PublishMonth', 'PublishDay', 'Publisher', 'RatingDist5', 'RatingDist4',
       'RatingDist3', 'RatingDist2', 'RatingDist1', 'RatingDistTotal',
       'CountsOfReview', 'Language', 'pagesNumber', 'Description',
       'Count of text reviews'])
for file in onlyfiles:
    temp = pd.read_csv('archive/' + file)
    if 'Description' in temp.columns:
        book = pd.concat([book, temp])

In [10]:
book

,Id,Name,Authors,ISBN,Rating,PublishYear,PublishMonth,PublishDay,Publisher,RatingDist5,...,RatingDist3,RatingDist2,RatingDist1,RatingDistTotal,CountsOfReview,Language,pagesNumber,Description,Count of text reviews,PagesNumber
0,1000000,Flight from Eden,Kathryn A. Graham,0595199402,4.00,2001,1,10,Writer's Showcase Press,5:1,...,3:1,2:0,1:0,total:3,1,NaN,380,"What could a computer expert, a mercenary with...",1,NaN
1,1000001,Roommates Again,Kathryn O. Galbraith,0689505973,3.20,1994,1,4,Margaret K. McElderry Books,5:0,...,3:1,2:0,1:1,total:5,1,NaN,44,"During their stay at Camp Sleep-Away, sisters ...",1,NaN
2,1000003,The King At The Door,Brock Cole,0374440417,3.95,1992,31,12,Farrar Straus Giroux,5:5,...,3:4,2:1,1:0,total:19,0,NaN,32,A poorly dressed old man appears at an inn and...,0,NaN
3,1000004,"Giotto: The Scrovegni Chapel, Padua",Bruce Cole,080761310X,4.47,1993,1,8,George Braziller,5:9,...,3:0,2:1,1:0,total:15,2,NaN,118,This beautiful series lavishly illustrates the...,2,NaN
4,1000005,Larky Mavis,Brock Cole,0374343659,3.69,2001,3,8,"Farrar, Straus and Giroux (BYR)",5:19,...,3:9,2:7,1:4,total:51,8,NaN,32,<b>Another orginal picture-book fairy tale</b>...,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40885,999991,Gendered Talk at Work: Constructing Gender Ide...,Janet Holmes,1405117591,4.28,2006,21,7,Wiley-Blackwell,5:15,...,3:6,2:1,1:0,total:25,0,NaN,251,<i>Gendered Talk at Work</i> examines how wome...,0,NaN
40886,999992,Good Will Toward Men: Women Talk Candidly abou...,Jack Kammer,0312104715,0.00,1994,1,2,St. Martin's Press,5:0,...,3:0,2:0,1:0,total:0,0,NaN,231,In interviews with gender issues journalist Ja...,0,NaN
40887,999993,Would You Rather . . . ?: The Outrageous Book ...,Randy Horn,0761124209,3.81,2001,1,10,Workman Publishing Company,5:39,...,3:34,2:11,1:2,total:121,14,NaN,400,<i>Would You Rather...?</i> takes the idea of ...,14,NaN
40888,999997,Addictions Treatment for Older Adults: Evaluat...,Kathryn Graham,1560248572,0.00,1995,2,2,Routledge,5:0,...,3:0,2:0,1:0,total:0,0,NaN,258,Here is a detailed description of an innovativ...,0,NaN
40889,999998,Within/Without,Kathryn T.S. Bass,097495974X,5.00,2005,1,3,"Pilgrims Process, Inc.",5:2,...,3:0,2:0,1:0,total:2,0,NaN,36,NaN,0,NaN

## Поиск и запись в файл датасета с запясями, где есть описание

In [18]:
book = book[~book['Description'].isna()] # а потом это to_csv
book = book[~book['Name'].duplicated()]     # Убираем дубликаты книг по названию
book.to_csv('book_with_description.csv')

# Работа с данными о юзерах

In [11]:
user = pd.DataFrame(columns=['ID', 'Name', 'Rating'])
for file in onlyfiles:
    if 'user' in file:
        user = pd.concat([user, pd.read_csv('archive/' + file)])

In [19]:
print(len(book))
print(len(user))

1064900
362596

In [12]:
user

,ID,Name,Rating
0,1,Agile Web Development with Rails: A Pragmatic ...,it was amazing
1,1,The Restaurant at the End of the Universe (Hit...,it was amazing
2,1,Siddhartha,it was amazing
3,1,The Clock of the Long Now: Time and Responsibi...,really liked it
4,1,"Ready Player One (Ready Player One, #1)",really liked it
...,...,...,...
127673,10978,The Foundation: A Great American Secret: How P...,liked it
127674,10986,Cosette: The Sequel to Les Miserables,really liked it
127675,10986,J. D. Salinger's The Catcher in the Rye,it was amazing
127676,10988,Facing the Lion: Growing Up Maasai on the Afri...,liked it
127677,10988,Homeless Bird,liked it

# Соединение БД

In [20]:
df = user.join(book[['Name', 'Description']].set_index('Name'), how='inner', on='Name')

In [33]:
df.to_csv('data.csv')

In [38]:
df

,ID,Name,Rating,Description
1,1,The Restaurant at the End of the Universe (Hit...,it was amazing,Just when you thought it was safe to go back t...
4163,73,The Restaurant at the End of the Universe (Hit...,really liked it,Just when you thought it was safe to go back t...
5262,116,The Restaurant at the End of the Universe (Hit...,it was amazing,Just when you thought it was safe to go back t...
7917,171,The Restaurant at the End of the Universe (Hit...,really liked it,Just when you thought it was safe to go back t...
19487,338,The Restaurant at the End of the Universe (Hit...,liked it,Just when you thought it was safe to go back t...
...,...,...,...,...
127659,10978,Smile As They Bow,liked it,"As the weeklong Taungbyon Festival draws near,..."
127668,10978,Speak Rwanda,really liked it,"""Speak Rwanda"" is the powerful story of ten pe..."
127670,10978,India After Gandhi: The History of the World's...,really liked it,Born against a background of privation and civ...
127676,10988,Facing the Lion: Growing Up Maasai on the Afri...,liked it,Joseph Lemasolai Lekuton gives American kids a...
127677,10988,Homeless Bird,liked it,"<blockquote>\n <i> ""What if I don't like him?..."

In [39]:
df.drop(['ID', 'Rating'], axis='columns').drop_duplicates().to_csv('book.csv')
df.drop(['Description'], axis='columns').drop_duplicates().to_csv('user.csv')

In [35]:
print(len(book))
print(len(temp))

1064900
106288

In [40]:
pd.read_csv('archive/book1800k-1900k.csv')

,Id,Name,Authors,ISBN,Rating,PublishYear,PublishMonth,PublishDay,Publisher,RatingDist5,RatingDist4,RatingDist3,RatingDist2,RatingDist1,RatingDistTotal,CountsOfReview,Language,PagesNumber,Description
0,1800000,Last Word: Media Coverage of the Supreme Court...,Florian Sauvageau,0774812435,5.00,2005,12,6,University of British Columbia Press,5:1,4:0,3:0,2:0,1:0,total:1,0,NaN,272,Media coverage of the Supreme Court of Canada ...
1,1800010,Murder on a Mystery Tour,Marian Babson,0802756689,3.20,2000,5,13,Walker & Company,5:21,4:73,3:121,2:42,1:10,total:267,26,NaN,182,<i>They had explored every avenue and it seeme...
2,1800011,Reel Murder: A Mystery,Marian Babson,0816144923,3.56,1988,12,31,G. K. Hall & Company,5:14,4:35,3:25,2:9,1:3,total:86,0,NaN,292,NaN
3,1800012,Principles of Bloodstain Pattern Analysis: The...,Stuart H. James,0849320143,4.58,2005,5,26,CRC Press,5:12,4:6,3:1,2:0,1:0,total:19,2,NaN,576,Bloodstain evidence has become a deciding fact...
4,1800013,The Encyclopedia of Crime Scene Investigation,Michael Newton,0816068151,4.00,2007,10,1,Checkmark Books,5:3,4:2,3:3,2:0,1:0,total:8,0,NaN,334,Recent years have brought numerous development...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38858,1899951,Painkillers and Tranquilizers,Michael Durham,1403408211,0.00,2003,4,1,Heinemann Educational Books,5:0,4:0,3:0,2:0,1:0,total:0,0,NaN,56,NaN
38859,1899957,Painkillers: Prescription Dependency,Ida Walker,1422201619,1.00,2008,1,1,Mason Crest Publishers,5:0,4:0,3:0,2:0,1:1,total:1,0,NaN,128,NaN
38860,1899961,On the Way to Krisna,A.C. Bhaktivedanta Swami Prabhupāda,0912776390,4.41,1991,2,1,Bhaktivedanta Book Trust,5:68,4:17,3:12,2:4,1:2,total:103,7,NaN,79,The Bhagavad-gita is the main source-book on y...
38861,1899962,Communicate to Win,Richard Denny,0749444355,3.76,2006,2,28,Kogan Page,5:15,4:15,3:20,2:4,1:0,total:54,1,NaN,131,Communication and motivation are essential for...
38862,1899976,Alcoholism and Treatment,David J. Armor,0471025585,0.00,1978,1,1,John Wiley & Sons,5:0,4:0,3:0,2:0,1:0,total:0,1,NaN,349,NaN

In [ ]:
# Код для удаления тегов и прочего